[package]
name = "ulo-graphql-async-graphql"
version = "0.1.0"
edition.workspace = true
rust-version = "1.89"
description = "The async-graphql engine for Ulo's GraphQL bindings"
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = ["ulo", "graphql", "async-graphql"]
categories = ["web-programming"]

[dependencies]
ulo = { path = "../ulo" }
ulo-graphql = { path = "../ulo-graphql" }
async-graphql = { workspace = true, features = ["graphiql"] }
futures-util.workspace = true
serde_json.workspace = true
